# Generated by Django 3.2.4 on 2021-06-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='', upload_to='movies/', verbose_name='Постер'),
        ),
    ]
