# Generated by Django 3.2.4 on 2021-06-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_alter_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='IP адрес')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
    ]
