# Generated by Django 3.2.4 on 2021-06-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0004_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-value'], 'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
    ]
